### ISSUE TITLE
Waltraud soll das Voicechannel-Chat lesen lernen

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/root#23]
Die neue Voice-Textys sind bei Psy freigeschaltet, sie sind für die Bots aber noch eine _terra icognita_.
Das ist ungünstig ~~muss sich ändern, koste es was es wolle~~ ⛵

**Comment by dnns01** [comment]
Slash Commands funktionieren out of the box auch in VC Chats
