### ISSUE TITLE
Willkommensnachricht leicht randomisieren

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/root#24]
Vor der Ankunft von Waltraud haben die Mods immer einen leichten persönlichen Touch in der Begrüßung eingebracht.
Beispielsweise mit einem anderen Emoji nach dem Username, als in der vorherigen Begrüßung.

**_Implementierung_**:
Siehe die Randomisierung der [Arminfunktion von Boty](https://github.com/FU-Hagen-Discord/fernuni-bot/blob/master/cogs/armin.py).

**Comment by dnns01** [comment]
Funktion existiert inzwischen, ist nur eine Frage der Konfiguration
